# Generated by Django 4.0.5 on 2022-06-28 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebookapi', '0003_alter_note_tags_alter_note_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='datetime',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
